import { NextResponse } from 'next/server';
import { z } from 'zod';
import { requireUser } from '@/lib/server-auth';
import { withRls, errorResponse } from '@/lib/db';
import { bumpUserCache } from '@/lib/redis';
const schema=z.object({notificationId:z.string().uuid(),action:z.enum(['accept','reject'])});
export async function POST(req:Request){try{const user=await requireUser();const input=schema.parse(await req.json());const result=await withRls(user.id,async tx=>{const n=await tx.notification.findFirst({where:{id:input.notificationId,userId:user.id},select:{id:true,type:true,shareRequestId:true,collabGroupJoinRequestId:true,collabCommitId:true}});if(!n)throw new Error('NOT_FOUND');
if(['share_request','collab_join_request'].includes(n.type)){if(!n.shareRequestId)throw new Error('REQUEST_NOT_FOUND');const inv=await tx.shareRequest.findUnique({where:{id:n.shareRequestId}});if(!inv||inv.status!=='pending')throw new Error('REQUEST_ALREADY_HANDLED');const isJoin=inv.requestType==='join';const allowed=isJoin?inv.receiverId===user.id:inv.receiverId===user.id;if(!allowed)throw new Error('FORBIDDEN');if(input.action==='accept'){const target=isJoin?inv.senderId:inv.receiverId;if(inv.scopeType==='roadmap'&&inv.roadmapId)await tx.roadmapShare.upsert({where:{roadmapId_userId:{roadmapId:inv.roadmapId,userId:target}},create:{roadmapId:inv.roadmapId,userId:target,role:inv.role==='editor'?'contributor':inv.role},update:{role:inv.role==='editor'?'contributor':inv.role}});else if(inv.scopeType==='topic'&&inv.rootTopicId)await tx.topicShare.upsert({where:{topicId_userId:{topicId:inv.rootTopicId,userId:target}},create:{topicId:inv.rootTopicId,userId:target,role:inv.role==='editor'?'contributor':inv.role},update:{role:inv.role==='editor'?'contributor':inv.role}});else if(inv.scopeType==='template'&&inv.templateId)await tx.templateShare.upsert({where:{templateId_userId:{templateId:inv.templateId,userId:target}},create:{templateId:inv.templateId,userId:target},update:{}});}const status=input.action==='accept'?'accepted':'rejected';const updated=await tx.shareRequest.update({where:{id:inv.id},data:{status}});await tx.notification.create({data:{userId:inv.senderId,type:`share_request_${status}`,title:isJoin?`Collaboration request ${status}`:`Share request ${status}`,body:isJoin?(status==='accepted'?'Your collaboration request was accepted.':'Your collaboration request was rejected.'):(status==='accepted'?'Your share request was accepted.':'Your share request was rejected.'),shareRequestId:inv.id}});await tx.notification.update({where:{id:n.id},data:{readAt:new Date()}});return {userIds:[inv.senderId,inv.receiverId],updated};}
if(n.type==='collab_group_join_request'){if(!n.collabGroupJoinRequestId)throw new Error('REQUEST_NOT_FOUND');const req=await tx.collabGroupJoinRequest.findUnique({where:{id:n.collabGroupJoinRequestId}});if(!req||req.status!=='pending')throw new Error('REQUEST_ALREADY_HANDLED');const group=await tx.collabGroup.findUnique({where:{id:req.groupId},select:{id:true,ownerId:true,maxMembers:true,name:true,roadmapId:true,settings:true}});if(!group)throw new Error('NOT_FOUND');const member=await tx.collabGroupMember.findUnique({where:{groupId_userId:{groupId:group.id,userId:user.id}},select:{id:true}});const settings=(group.settings as any)||{};const kind=settings.kind==='community'?'community':'team';const can=kind==='community'?group.ownerId===user.id:(group.ownerId===user.id||!!member);if(!can)throw new Error('FORBIDDEN');if(input.action==='accept'){await tx.$queryRaw`select id from collab_groups where id=${group.id}::uuid for update`;const existing=await tx.collabGroupMember.findUnique({where:{groupId_userId:{groupId:group.id,userId:req.requesterId}}});if(!existing){const count=await tx.collabGroupMember.count({where:{groupId:group.id}});if(count>=group.maxMembers)throw new Error('GROUP_FULL');await tx.collabGroupMember.create({data:{groupId:group.id,userId:req.requesterId,role:'editor'}});const ids=Array.from(new Set([group.roadmapId,...((settings.roadmapIds||[]) as string[])]));for(const rid of ids)await tx.roadmapShare.upsert({where:{roadmapId_userId:{roadmapId:rid,userId:req.requesterId}},create:{roadmapId:rid,userId:req.requesterId,role:'contributor'},update:{role:'contributor'}});await tx.notification.create({data:{userId:req.requesterId,type:'collab_group_join_result',title:`Joined ${group.name}`,body:`Your request to join ${kind} ${group.name} was accepted.`,collabGroupJoinRequestId:req.id}});}}else await tx.notification.create({data:{userId:req.requesterId,type:'collab_group_join_result',title:'Join request rejected',body:`Your request to join ${group.name} was rejected.`,collabGroupJoinRequestId:req.id}});const updated=await tx.collabGroupJoinRequest.update({where:{id:req.id},data:{status:input.action==='accept'?'accepted':'rejected',reviewedBy:user.id,reviewedAt:new Date()}});await tx.notification.update({where:{id:n.id},data:{readAt:new Date()}});return {userIds:[req.requesterId,user.id],updated};}
if(n.type==='collab_commit_pushed'){
 const commit=await tx.collabCommit.findUnique({where:{id:n.collabCommitId||''},include:{branch:true}});
 if(!commit)throw new Error('REQUEST_NOT_FOUND');
 if(commit.branch.roadmapId===undefined)throw new Error('NOT_FOUND');
 const roadmap=await tx.roadmap.findUnique({where:{id:commit.branch.roadmapId},select:{ownerId:true,version:true}});
 if(!roadmap||roadmap.ownerId!==user.id)throw new Error('FORBIDDEN');
 if(!['pending','conflict'].includes(commit.status))throw new Error('REQUEST_ALREADY_HANDLED');
 if(input.action==='accept'){
   if(roadmap.version!==commit.baseVersion){await tx.collabCommit.update({where:{id:commit.id},data:{status:'conflict'}});throw new Error('MERGE_CONFLICT');}
   const { mergeSnapshot } = await import('@/lib/collab-branch');
   const { recordChange } = await import('@/lib/collab-access');
   await mergeSnapshot(tx,commit.snapshot as any,commit.branch.rootTopicId);
   await recordChange(tx,commit.branch.roadmapId,user.id,`merge:${commit.message}`,'commit',commit.id,{commitId:commit.id,branchId:commit.branchId,authorId:commit.authorId});
   await tx.collabCommit.update({where:{id:commit.id},data:{status:'merged',mergedAt:new Date(),mergedBy:user.id}});
   await tx.collabBranch.update({where:{id:commit.branchId},data:{status:'merged'}});
 } else await tx.collabCommit.update({where:{id:commit.id},data:{status:'rejected'}});
 await tx.notification.update({where:{id:n.id},data:{readAt:new Date()}});
 await tx.notification.create({data:{userId:commit.authorId,type:input.action==='accept'?'collab_commit_merged':'collab_commit_rejected',collabCommitId:commit.id,title:input.action==='accept'?'Commit merged':'Commit rejected',body:input.action==='accept'?'Your commit was accepted by the roadmap leader.':'Your commit was rejected by the roadmap leader.'}});
 return {userIds:[commit.authorId,user.id],updated:commit};
}
throw new Error('NOT_ACTIONABLE');});await bumpUserCache(result.userIds);return NextResponse.json({ok:true,...result});}catch(e){return errorResponse(e)}}
