import { NextResponse } from 'next/server';
import { withRls, errorResponse } from '@/lib/db';
import { requireUser } from '@/lib/server-auth';
import { z } from 'zod';
import { getCached, setCached, userCacheKey, bumpUserCache } from '@/lib/redis';
const schema=z.object({scopeType:z.enum(['roadmap','topic','template']),role:z.enum(['contributor','editor','viewer']).default('contributor'),roadmapId:z.string().uuid().nullable().default(null),rootTopicId:z.string().uuid().nullable().default(null),templateId:z.string().uuid().nullable().default(null),receiverId:z.string().trim().min(1).max(255),message:z.string().max(1000).default('')});
export async function POST(req:Request){try{const user=await requireUser();const input=schema.parse(await req.json());if(input.receiverId===user.id)throw new Error('Cannot send to yourself');const receiver=await withRls(user.id,tx=>tx.user.findUnique({where:{id:input.receiverId},select:{id:true}}));if(!receiver)throw new Error('RECEIVER_NOT_FOUND');const invite=await withRls(user.id,async tx=>{let title='Template';if(input.scopeType==='roadmap'){if(!input.roadmapId)throw new Error('ROADMAP_REQUIRED');const roadmap=await tx.roadmap.findFirst({where:{id:input.roadmapId,ownerId:user.id}});if(!roadmap)throw new Error('NOT_FOUND');title=roadmap.title}else if(input.scopeType==='topic'){if(!input.roadmapId||!input.rootTopicId)throw new Error('TOPIC_REQUIRED');const topic=await tx.topic.findFirst({where:{id:input.rootTopicId,roadmapId:input.roadmapId,roadmap:{ownerId:user.id}}});if(!topic)throw new Error('NOT_FOUND');title=topic.title}else{if(!input.templateId)throw new Error('TEMPLATE_REQUIRED');const template=await tx.template.findUnique({where:{id:input.templateId}});if(!template)throw new Error('NOT_FOUND');title=template.name}const existing=await tx.shareRequest.findFirst({where:{scopeType:input.scopeType,roadmapId:input.roadmapId,rootTopicId:input.rootTopicId,templateId:input.templateId,senderId:user.id,receiverId:input.receiverId,status:'pending'}});if(existing)throw new Error('A pending request already exists');const request=await tx.shareRequest.create({data:{scopeType:input.scopeType,roadmapId:input.roadmapId,rootTopicId:input.rootTopicId,templateId:input.templateId,senderId:user.id,receiverId:input.receiverId,message:input.message,role:input.role}});
      let body=input.message||`You have received a ${input.scopeType} share request.`;
      await tx.notification.create({data:{userId:input.receiverId,type:'share_request',title:`Share request: ${title}`,body,shareRequestId:request.id}});return request});await bumpUserCache([user.id, input.receiverId]);return NextResponse.json({shareRequest:invite},{status:201})}catch(e){return errorResponse(e)}}
export async function GET(req:Request){try{const user=await requireUser();const sent=new URL(req.url).searchParams.get('sent')==='1';const key=await userCacheKey(user.id,'share-requests',sent?'sent':'received');const cached=await getCached<any[]>(key);if(cached)return NextResponse.json({items:cached,cached:true});const items=await withRls(user.id,tx=>tx.shareRequest.findMany({where:sent?{senderId:user.id}:{receiverId:user.id,status:'pending'},include:{roadmap:true,rootTopic:true,template:true},orderBy:{createdAt:'desc'},take:100}));await setCached(key,items,10);return NextResponse.json({items,cached:false})}catch(e){return errorResponse(e)}}
