'use client';
import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { AuthMessage, AuthShell } from '@/components/auth-form';
import { Button } from '@/components/ui';
import { authAction } from '@/lib/auth-client';

export default function Signup(){
 const[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[otp,setOtp]=useState(''),[userId,setUserId]=useState(''),[msg,setMsg]=useState(''),[loading,setLoading]=useState(false),[verified,setVerified]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();if(password!==confirm){setMsg('Passwords do not match.');return}setLoading(true);setMsg('');try{const data=await authAction<{requiresOtp:boolean;userId:string;message:string}>('/api/auth/signup',{name,email,password});setUserId(data.userId);setMsg(data.message);}catch(err){setMsg(err instanceof Error?err.message:'Unable to create account.')}finally{setLoading(false)}}
 async function verify(e:FormEvent){e.preventDefault();setLoading(true);setMsg('');try{await authAction('/api/auth/signup/verify',{userId,otp});try{localStorage.setItem('roadmap:last-activity',String(Date.now()));}catch{} setVerified(true);location.href='/dashboard';}catch(err){setMsg(err instanceof Error?err.message:'Invalid verification code.')}finally{setLoading(false)}}
 async function resend(){setLoading(true);setMsg('');try{const d=await authAction<{message:string}>('/api/auth/signup/resend',{userId});setMsg(d.message)}catch(err){setMsg(err instanceof Error?err.message:'Unable to resend code.')}finally{setLoading(false)}}
 return <AuthShell title={userId?'Verify your email':'Create your Roadmap account'} subtitle={userId?'Enter the 6-digit code we sent to your email.':'Build a learning system that compounds over time.'} footer={<>Already have an account? <Link href="/auth/login" className="text-indigo-600 hover:underline">Login</Link></>}>
 {!userId ? <form onSubmit={submit} className="space-y-4"><label className="block text-sm font-medium">Full name<input required value={name} onChange={e=>setName(e.target.value)} className="mt-1.5 w-full rounded-xl border border-[hsl(var(--line))] bg-transparent px-3 py-2.5"/></label><label className="block text-sm font-medium">Email<input autoComplete="email" required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-1.5 w-full rounded-xl border border-[hsl(var(--line))] bg-transparent px-3 py-2.5"/></label><label className="block text-sm font-medium">Password<input autoComplete="new-password" required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1.5 w-full rounded-xl border border-[hsl(var(--line))] bg-transparent px-3 py-2.5"/></label><label className="block text-sm font-medium">Confirm password<input autoComplete="new-password" required minLength={8} type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} className="mt-1.5 w-full rounded-xl border border-[hsl(var(--line))] bg-transparent px-3 py-2.5"/></label><Button type="submit" disabled={loading} className="w-full">{loading?'Sending code…':'Create account'}</Button><AuthMessage message={msg} error/></form> : <form onSubmit={verify} className="space-y-4"><div className="rounded-xl border border-[hsl(var(--line))] bg-[hsl(var(--bg))] p-3 text-sm">Code sent to <b>{email}</b>. It expires in 10 minutes.</div><label className="block text-sm font-medium">Verification code<input inputMode="numeric" autoComplete="one-time-code" required pattern="[0-9]{6}" maxLength={6} value={otp} onChange={e=>setOtp(e.target.value.replace(/\D/g,'').slice(0,6))} className="mt-1.5 w-full rounded-xl border border-[hsl(var(--line))] bg-transparent px-3 py-2.5 text-center text-xl tracking-[0.4em]"/></label><Button type="submit" disabled={loading||otp.length!==6} className="w-full">{loading?'Verifying…':'Verify and continue'}</Button><button type="button" onClick={resend} disabled={loading} className="w-full text-sm font-medium text-indigo-600 hover:underline">Resend code</button><AuthMessage message={msg} error/></form>}
 </AuthShell>
}
