'use client';
import { useEffect, useMemo, useState } from 'react';
import { AppShell } from '@/components/app-shell';
import { Card, Button } from '@/components/ui';
import { CalendarDays, Check, ChevronLeft, ChevronRight, Pencil, Plus, Save, Trash2, X } from 'lucide-react';

type Todo={id:string;todoDate:string;title:string;notes:string;completed:boolean;position:number;roadmapId:string|null;topicId:string|null};
type Log={logDate:string;studyMinutes:number;topicsStudied:string[];resourcesCompleted:number;problemsSolved:number;learned:string;difficulties:string;tomorrowGoal:string};
const iso=(d:Date)=>d.toISOString().slice(0,10);
const emptyLog=(d:string):Log=>({logDate:d,studyMinutes:0,topicsStudied:[],resourcesCompleted:0,problemsSolved:0,learned:'',difficulties:'',tomorrowGoal:''});
const startOfMonth=(d:Date)=>new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),1));
const monthLabel=(d:Date)=>d.toLocaleDateString('en-US',{month:'long',year:'numeric',timeZone:'UTC'});

export default function Calendar(){
  const today=useMemo(()=>new Date(),[]); const initialDate=useMemo(()=>{const value=new URLSearchParams(typeof window==='undefined'?'':window.location.search).get('date');return value && /^\d{4}-\d{2}-\d{2}$/.test(value)?value:iso(today)},[today]); const [month,setMonth]=useState(()=>startOfMonth(new Date(`${initialDate}T00:00:00.000Z`))); const [selected,setSelected]=useState(initialDate);
  const [logs,setLogs]=useState<Log[]>([]); const [todos,setTodos]=useState<Todo[]>([]); const [stats,setStats]=useState<any>({});
  const [form,setForm]=useState<Log>(emptyLog(selected)); const [title,setTitle]=useState(''); const [notes,setNotes]=useState(''); const [editing,setEditing]=useState<string|null>(null); const [saving,setSaving]=useState(false);
  const monthDays=useMemo(()=>{const first=startOfMonth(month);const offset=first.getUTCDay();const daysInMonth=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0)).getUTCDate();const cells:Array<Date|null>=Array.from({length:offset},()=>null);for(let i=1;i<=daysInMonth;i++)cells.push(new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth(),i)));while(cells.length%7)cells.push(null);return cells},[month]);
  const rangeStart=new Date(Date.UTC(month.getUTCFullYear(),month.getUTCMonth(),1)); rangeStart.setUTCDate(1-rangeStart.getUTCDay()); const rangeEnd=new Date(rangeStart); rangeEnd.setUTCDate(rangeStart.getUTCDate()+41);
  async function load(){const [l,t]=await Promise.all([fetch(`/api/daily-logs?from=${iso(rangeStart)}&to=${iso(rangeEnd)}&today=${iso(today)}`),fetch(`/api/todos?from=${iso(rangeStart)}&to=${iso(rangeEnd)}`)]);const lj=await l.json();const tj=await t.json();setLogs(lj.logs||[]);setStats(lj.stats||{});setTodos(tj.todos||[])}
  useEffect(()=>{load()},[month]);
  useEffect(()=>{setForm(logs.find(x=>x.logDate.slice(0,10)===selected)||emptyLog(selected))},[selected,logs]);
  const logMap=new Map(logs.map(l=>[l.logDate.slice(0,10),l])); const selectedTodos=todos.filter(t=>t.todoDate.slice(0,10)===selected).sort((a,b)=>a.position-b.position);
  function pickDate(k:string){setSelected(k);setEditing(null);setTitle('');setNotes('')}
  async function saveLog(){setSaving(true);const r=await fetch('/api/daily-logs',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,logDate:selected})});setSaving(false);if(!r.ok)alert(await r.text());else load()}
  async function addTodo(){if(!title.trim())return;setSaving(true);const r=await fetch('/api/todos',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({todoDate:selected,title:title.trim(),notes:notes.trim()})});setSaving(false);if(!r.ok)return alert(await r.text());setTitle('');setNotes('');await load()}
  async function updateTodo(t:Todo){if(!title.trim())return;setSaving(true);const r=await fetch(`/api/todos/${t.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:title.trim(),notes:notes.trim()})});setSaving(false);if(!r.ok)return alert(await r.text());setEditing(null);setTitle('');setNotes('');await load()}
  async function toggleTodo(t:Todo){const r=await fetch(`/api/todos/${t.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({completed:!t.completed})});if(r.ok)load()}
  async function deleteTodo(t:Todo){if(!confirm(`Delete “${t.title}”?`))return;const r=await fetch(`/api/todos/${t.id}`,{method:'DELETE'});if(r.ok)load()}
  function beginEdit(t:Todo){setEditing(t.id);setTitle(t.title);setNotes(t.notes||'')}
  return <AppShell>
    <header className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><div className="flex items-center gap-2"><CalendarDays size={20} className="text-indigo-600"/><h1 className="text-2xl font-bold tracking-tight">Learning Calendar</h1></div><p className="mt-1 text-sm text-slate-500">Select a date to manage its plan and learning log.</p></div><div className="flex items-center gap-2"><Button variant="outline" onClick={()=>setMonth(new Date(Date.UTC(month.getUTCFullYear(),month.getUTCMonth()-1,1)))}><ChevronLeft size={16}/></Button><div className="min-w-36 text-center text-sm font-semibold">{monthLabel(month)}</div><Button variant="outline" onClick={()=>setMonth(new Date(Date.UTC(month.getUTCFullYear(),month.getUTCMonth()+1,1)))}><ChevronRight size={16}/></Button><Button variant="outline" onClick={()=>{setMonth(startOfMonth(today));pickDate(iso(today))}}>Today</Button></div></header>
    <Card className="p-4 sm:p-5"><div className="mb-2 grid grid-cols-7 text-center text-[10px] font-medium uppercase tracking-wide text-slate-400">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=><span key={x}>{x}</span>)}</div><div className="grid grid-cols-7 gap-1.5">{monthDays.map((d,i)=>{if(!d)return <div key={`e-${i}`} className="aspect-square"/>;const k=iso(d),log=logMap.get(k);const active=!!log?.studyMinutes||todos.some(t=>t.todoDate.slice(0,10)===k);const isSelected=k===selected;return <button key={k} onClick={()=>pickDate(k)} className={`relative aspect-square rounded-lg border text-xs transition ${isSelected?'border-indigo-500 bg-indigo-50 text-indigo-700 ring-2 ring-indigo-500/20 dark:bg-indigo-950/40 dark:text-indigo-300':'border-transparent hover:border-[hsl(var(--line))] hover:bg-slate-50 dark:hover:bg-slate-900'} ${active?'font-semibold':''}`}><span>{d.getUTCDate()}</span>{active&&<span className="absolute bottom-1 left-1/2 h-1 w-1 -translate-x-1/2 rounded-full bg-indigo-500"/>}</button>})}</div></Card>
    <div className="mt-4 grid gap-4 xl:grid-cols-[.9fr_1.1fr]"><Card className="p-4 sm:p-5"><div className="flex items-start justify-between"><div><div className="text-xs font-semibold uppercase tracking-wide text-indigo-600">Selected date</div><h2 className="mt-1 text-lg font-semibold">{selected}</h2></div><div className="text-right text-xs text-slate-500"><div>{stats.currentStreak||0} day streak</div><div>{Math.floor((stats.totalStudyMinutes||0)/60)}h {(stats.totalStudyMinutes||0)%60}m total</div></div></div>
      <div className="mt-4 border-t border-[hsl(var(--line))] pt-4"><div className="mb-2 text-sm font-semibold">Todos</div><div className="flex flex-col gap-2 sm:flex-row"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder={editing?'Update todo title':'Add a todo for this date'} className="min-w-0 flex-1 rounded-xl border border-[hsl(var(--line))] bg-transparent px-3 py-2 text-sm"/><input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Notes (optional)" className="min-w-0 flex-1 rounded-xl border border-[hsl(var(--line))] bg-transparent px-3 py-2 text-sm"/>{editing?<><Button onClick={()=>updateTodo(selectedTodos.find(t=>t.id===editing)!)} disabled={saving}><Save size={15}/></Button><Button variant="outline" onClick={()=>{setEditing(null);setTitle('');setNotes('')}}><X size={15}/></Button></>:<Button onClick={addTodo} disabled={saving}><Plus size={15}/></Button>}</div>
      <div className="mt-3 space-y-2">{selectedTodos.map(t=><div key={t.id} className="flex items-center gap-2 rounded-xl border border-[hsl(var(--line))] px-3 py-2.5"><button onClick={()=>toggleTodo(t)} className={`grid size-7 shrink-0 place-items-center rounded-lg border ${t.completed?'border-indigo-600 bg-indigo-600 text-white':'border-[hsl(var(--line))]'}`}><Check size={14}/></button><div className="min-w-0 flex-1"><div className={`truncate text-sm ${t.completed?'text-slate-400 line-through':''}`}>{t.title}</div>{t.notes&&<div className="truncate text-xs text-slate-400">{t.notes}</div>}</div><button onClick={()=>beginEdit(t)} className="rounded-lg p-1.5 text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800"><Pencil size={15}/></button><button onClick={()=>deleteTodo(t)} className="rounded-lg p-1.5 text-red-500 hover:bg-red-50 dark:hover:bg-red-950/30"><Trash2 size={15}/></button></div>)}{!selectedTodos.length&&<div className="rounded-xl border border-dashed border-[hsl(var(--line))] p-4 text-center text-sm text-slate-400">No todos yet. Add one above.</div>}</div></div></Card>
      <Card className="p-4 sm:p-5"><div className="flex items-center justify-between"><div><div className="text-sm font-semibold">Daily learning log</div><div className="text-xs text-slate-500">Everything saved against {selected}</div></div><Button onClick={saveLog} disabled={saving}><Save size={15}/> Save</Button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-medium">Study minutes<input type="number" min="0" value={form.studyMinutes} onChange={e=>setForm({...form,studyMinutes:+e.target.value})} className="mt-1 w-full rounded-xl border border-[hsl(var(--line))] bg-transparent px-3 py-2"/></label><label className="text-xs font-medium">Problems solved<input type="number" min="0" value={form.problemsSolved} onChange={e=>setForm({...form,problemsSolved:+e.target.value})} className="mt-1 w-full rounded-xl border border-[hsl(var(--line))] bg-transparent px-3 py-2"/></label><label className="text-xs font-medium">Resources completed<input type="number" min="0" value={form.resourcesCompleted} onChange={e=>setForm({...form,resourcesCompleted:+e.target.value})} className="mt-1 w-full rounded-xl border border-[hsl(var(--line))] bg-transparent px-3 py-2"/></label><label className="text-xs font-medium">Topics studied<input value={form.topicsStudied.join(', ')} onChange={e=>setForm({...form,topicsStudied:e.target.value.split(',').map(x=>x.trim()).filter(Boolean)})} className="mt-1 w-full rounded-xl border border-[hsl(var(--line))] bg-transparent px-3 py-2"/></label><label className="text-xs font-medium sm:col-span-2">What I learned<textarea value={form.learned} onChange={e=>setForm({...form,learned:e.target.value})} className="mt-1 h-20 w-full rounded-xl border border-[hsl(var(--line))] bg-transparent p-2.5"/></label><label className="text-xs font-medium sm:col-span-2">Difficulties<textarea value={form.difficulties} onChange={e=>setForm({...form,difficulties:e.target.value})} className="mt-1 h-20 w-full rounded-xl border border-[hsl(var(--line))] bg-transparent p-2.5"/></label><label className="text-xs font-medium sm:col-span-2">Tomorrow's goal<textarea value={form.tomorrowGoal} onChange={e=>setForm({...form,tomorrowGoal:e.target.value})} className="mt-1 h-20 w-full rounded-xl border border-[hsl(var(--line))] bg-transparent p-2.5"/></label></div></Card></div>
  </AppShell>
}
