import { NextResponse } from 'next/server';
import { withRls, errorResponse } from '@/lib/db';
import { requireUser } from '@/lib/server-auth';
import { z } from 'zod';
import { getCached, setCached, userCacheKey, bumpUserCache } from '@/lib/redis';
const schema=z.object({roadmapId:z.string().uuid().nullable().default(null),topicId:z.string().uuid().nullable().default(null),todoDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),title:z.string().trim().min(1).max(300),notes:z.string().max(5000).default(''),completed:z.boolean().default(false),priority:z.number().int().min(0).max(3).default(0),visibility:z.enum(['private','friends']).default('private')});
const dateOnly=(s:string)=>new Date(`${s}T00:00:00.000Z`);

export async function GET(req:Request){try{const user=await requireUser();const q=new URL(req.url).searchParams;const date=q.get('date');const from=q.get('from');const to=q.get('to');const key = await userCacheKey(user.id, 'todos', `${date || ''}:${from || ''}:${to || ''}`); const cached = await getCached<any[]>(key); if (cached) return NextResponse.json({todos: cached, cached: true}); const todos=await withRls(user.id,tx=>tx.todo.findMany({where:{OR:[{ownerId:user.id},{visibility:'friends',roadmapId:{not:null},roadmap:{shares:{some:{userId:user.id}}}}],...(date?{todoDate:dateOnly(date)}:{...(from||to?{todoDate:{...(from?{gte:dateOnly(from)}:{}),...(to?{lte:dateOnly(to)}:{})}}:{})})},orderBy:[{todoDate:'asc'},{position:'asc'},{createdAt:'asc'}]}));await setCached(key, todos, 20); return NextResponse.json({todos, cached: false});}catch(e){return errorResponse(e)}}
export async function POST(req:Request){try{const user=await requireUser();const input=schema.parse(await req.json());const todo=await withRls(user.id,async tx=>{let roadmapOwner=false; if(input.roadmapId){const r=await tx.roadmap.findFirst({where:{id:input.roadmapId},select:{ownerId:true}});if(!r)throw new Error('NOT_FOUND');roadmapOwner=r.ownerId===user.id;if(!roadmapOwner&&!input.visibility)throw new Error('NOT_FOUND');} if(input.visibility==='friends' && !input.roadmapId) throw new Error('FRIENDS_REQUIRES_ROADMAP'); if(input.visibility==='friends' && input.roadmapId && !roadmapOwner){const share=await tx.roadmapShare.findFirst({where:{roadmapId:input.roadmapId,userId:user.id}}); if(!share) throw new Error('FRIENDS_REQUIRES_SHARED_ROADMAP')} if(input.roadmapId&&!roadmapOwner){throw new Error('NOT_FOUND')} if(input.topicId){const t=await tx.topic.findFirst({where:{id:input.topicId,roadmap:{ownerId:user.id}}});if(!t)throw new Error('NOT_FOUND')}const max=await tx.todo.aggregate({where:{ownerId:user.id,todoDate:dateOnly(input.todoDate)},_max:{position:true}});return tx.todo.create({data:{ownerId:user.id,roadmapId:input.roadmapId,topicId:input.topicId,todoDate:dateOnly(input.todoDate),title:input.title,notes:input.notes,completed:input.completed,priority:input.priority,position:(max._max.position??-1)+1,visibility:input.visibility}})});await bumpUserCache(user.id);return NextResponse.json({todo},{status:201})}catch(e){return errorResponse(e)}}
