'use client';
import { useMemo } from 'react';
import { useGetJsonQuery, useRequestMutation } from '@/lib/redux/api';
import { Badge, Button, Card } from './ui';
import { Bell, CheckCheck, Clock3 } from 'lucide-react';
type Notice={id:string;type:string;title:string;body:string;readAt:string|null;createdAt:string;roadmapId?:string|null;roadmapShareSlug?:string|null;roadmapPrivacy?:string|null};
const ACTIONABLE=new Set(['collab_group_join_request','collab_join_request','share_request','collab_commit_pushed']);
export default function NotificationsClient({ initialItems: _initialItems }: { initialItems?: Notice[] }){
  const {data,isLoading:loading}=useGetJsonQuery({url:'/api/notifications',tag:'notifications'});
  const [request]=useRequestMutation();
  const items=(((data as any)?.notifications||[]) as Notice[]);
  const unread=useMemo(()=>items.filter(x=>!x.readAt).length,[items]);
  const mark=async(id?:string)=>{try{await request({url:'/api/notifications',method:'PATCH',body:id?{id}:{},invalidate:['notifications']}).unwrap()}catch(e){alert(e instanceof Error?e.message:'Unable to update notifications')}};
  const openRoadmap=(id:string)=>{ window.location.href=`/roadmap/${id}/live`; };
  const clone=async(id:string)=>{try{const j:any=await request({url:'/api/notifications/clone',method:'POST',body:{notificationId:id},invalidate:['notifications','roadmaps']}).unwrap();window.location.href=`/roadmap/${j.roadmap.id}`;}catch(e){alert(e instanceof Error?e.message:'Could not clone roadmap')}};
  const respond=async(id:string,action:'accept'|'reject')=>{try{await request({url:'/api/notifications/action',method:'POST',body:{notificationId:id,action},invalidate:['notifications','share-requests-received','share-requests-sent','shared-mine','communities']}).unwrap();}catch(e){alert(e instanceof Error?e.message:'Could not process request.')}};
  return <><header className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><div className="flex items-center gap-2"><Bell className="text-indigo-600" size={21}/><h1 className="text-3xl font-bold">Notifications</h1><Badge>{unread} unread</Badge></div><p className="mt-2 text-sm text-slate-500">Shares, requests, collaboration and account activity.</p></div><Button variant="outline" onClick={()=>mark()} disabled={!unread||loading}><CheckCheck size={15}/> Mark all read</Button></header><Card className="p-5">{loading?<div className="flex justify-center py-10"><span className="studio-spinner"/></div>:<div className="space-y-2">{items.map(n=><div key={n.id} className={`rounded-2xl border p-4 ${n.readAt?'border-[hsl(var(--line))]':'border-indigo-200 bg-indigo-50/50 dark:border-indigo-900/50 dark:bg-indigo-950/20'}`}><div className="flex items-start gap-3"><div className="grid size-9 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-500 dark:bg-slate-900"><Bell size={16}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-sm font-semibold">{n.title}</h2>{!n.readAt&&<Badge>New</Badge>}</div><p className="mt-1 whitespace-pre-wrap text-sm text-slate-500">{n.body}</p><div className="mt-2 flex items-center gap-2 text-[11px] text-slate-400"><Clock3 size={12}/> {new Date(n.createdAt).toLocaleString()}</div>{n.roadmapId&&<div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>openRoadmap(n.roadmapId!)}>Open roadmap</Button>{(!n.readAt || n.type==='roadmap_shared' || n.type==='share_request_accepted' || n.type==='collab_group_join_result' || n.type==='collab_commit_merged')&&<Button size="sm" variant="outline" onClick={()=>void clone(n.id)}>Clone</Button>}{n.roadmapPrivacy!=='public'&&!['collab_join_request','collab_group_join_request'].includes(n.type)&&<Button size="sm" onClick={()=>openRoadmap(n.roadmapId!)}>Collaborate</Button>}</div>}{!n.readAt&&ACTIONABLE.has(n.type)&&<div className="mt-3 flex flex-wrap gap-2"><Button size="sm" onClick={()=>respond(n.id,'accept')}><CheckCheck size={14}/> Approve</Button><Button size="sm" variant="outline" onClick={()=>respond(n.id,'reject')}>Reject</Button></div>}</div>{!n.readAt&&!ACTIONABLE.has(n.type)&&<Button variant="outline" onClick={()=>mark(n.id)} className="shrink-0 text-xs">Read</Button>}</div></div>)}{!items.length&&<div className="py-12 text-center text-sm text-slate-400">No notifications right now.</div>}</div>}</Card></>;
}
