'use client';
import { useEffect, useState } from 'react';
import { useGetJsonQuery, useRequestMutation } from '@/lib/redux/api';
import { AppShell } from '@/components/app-shell';
import { Card, Button } from '@/components/ui';

export default function Settings(){
 const{data:meData}=useGetJsonQuery({url:'/api/me',tag:'me'});
 const[user, setUser]=useState<any>(null);
 const[profile,setProfile]=useState({fullName:'',avatarUrl:'',bio:''}); const[busy,setBusy]=useState(false);
 const[passwordOtp,setPasswordOtp]=useState(''); const[newPassword,setNewPassword]=useState(''); const[passwordSent,setPasswordSent]=useState(false); const[passwordMsg,setPasswordMsg]=useState(''); const[passwordBusy,setPasswordBusy]=useState(false);
 const[request]=useRequestMutation();
 useEffect(()=>{if(!meData)return;const j=meData as any;setUser(j.user);setProfile({fullName:j.profile?.fullName??'',avatarUrl:j.profile?.avatarUrl??'',bio:j.profile?.bio??''})},[meData]);
 async function save(){setBusy(true);try{await request({url:'/api/me',method:'PATCH',body:profile,invalidate:['me']}).unwrap();alert('Profile saved.')}catch(e){alert(e instanceof Error?e.message:'Unable to save profile')}finally{setBusy(false)}}
 async function sendPasswordOtp(){setPasswordBusy(true);setPasswordMsg('');try{const r=await fetch('/api/auth/password/otp',{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to send OTP.');setPasswordSent(true);setPasswordMsg(d.message)}catch(e){setPasswordMsg(e instanceof Error?e.message:'Unable to send OTP.')}finally{setPasswordBusy(false)}}
 async function updatePassword(){setPasswordBusy(true);setPasswordMsg('');try{const r=await fetch('/api/auth/password/update',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({otp:passwordOtp,password:newPassword})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to update password.');setPasswordMsg(d.message);setPasswordOtp('');setNewPassword('');setPasswordSent(false)}catch(e){setPasswordMsg(e instanceof Error?e.message:'Unable to update password.')}finally{setPasswordBusy(false)}}
 return <AppShell><header className="mb-6"><h1 className="text-3xl font-bold">Settings</h1><p className="mt-1 text-slate-500">Your account identity and profile.</p></header><div className="grid gap-5 md:grid-cols-2">
 <Card className="p-6"><h2 className="font-semibold">Roadmap User ID</h2><p className="mt-2 text-sm text-slate-500">Give this ID to another Roadmap user when they want to share a roadmap with you.</p><div className="mt-4 flex gap-2"><input readOnly value={user?.id??''} className="min-w-0 flex-1 rounded-xl border border-[hsl(var(--line))] bg-slate-50 px-3 py-2 font-mono text-xs dark:bg-slate-900"/><Button variant="outline" onClick={()=>navigator.clipboard?.writeText(user?.id??'')}>Copy ID</Button></div><p className="mt-3 text-xs text-slate-500">Email: {user?.email??'—'}</p></Card>
 <Card className="p-6"><h2 className="font-semibold">Profile</h2><div className="mt-4 space-y-3"><label className="block text-sm font-medium">Name<input value={profile.fullName} onChange={e=>setProfile({...profile,fullName:e.target.value})} className="mt-1 w-full rounded-xl border border-[hsl(var(--line))] bg-transparent px-3 py-2"/></label><label className="block text-sm font-medium">Avatar URL<input value={profile.avatarUrl} onChange={e=>setProfile({...profile,avatarUrl:e.target.value})} className="mt-1 w-full rounded-xl border border-[hsl(var(--line))] bg-transparent px-3 py-2"/></label><label className="block text-sm font-medium">Bio<textarea value={profile.bio} onChange={e=>setProfile({...profile,bio:e.target.value})} className="mt-1 h-28 w-full rounded-xl border border-[hsl(var(--line))] bg-transparent p-3"/></label><Button onClick={save} disabled={busy}>{busy?'Saving…':'Save profile'}</Button></div></Card>
 <Card className="p-6 md:col-span-2"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">Update password</h2><p className="mt-1 text-sm text-slate-500">We’ll send a one-time code to your account email before changing your password.</p></div><Button variant="outline" onClick={sendPasswordOtp} disabled={passwordBusy}>{passwordSent?'Resend OTP':'Send OTP'}</Button></div>{passwordSent&&<div className="mt-4 grid gap-3 md:grid-cols-2"><label className="block text-sm font-medium">OTP<input inputMode="numeric" autoComplete="one-time-code" maxLength={6} value={passwordOtp} onChange={e=>setPasswordOtp(e.target.value.replace(/\D/g,'').slice(0,6))} className="mt-1 w-full rounded-xl border border-[hsl(var(--line))] bg-transparent px-3 py-2"/></label><label className="block text-sm font-medium">New password<input type="password" minLength={8} value={newPassword} onChange={e=>setNewPassword(e.target.value)} className="mt-1 w-full rounded-xl border border-[hsl(var(--line))] bg-transparent px-3 py-2"/></label><Button onClick={updatePassword} disabled={passwordBusy||passwordOtp.length!==6||newPassword.length<8} className="md:col-span-2">{passwordBusy?'Updating…':'Update password'}</Button></div>}<p className="mt-3 text-sm text-slate-500">{passwordMsg}</p></Card>
 </div></AppShell>
}
