import { NextResponse } from 'next/server';
import { withRls, errorResponse } from '@/lib/db';
import { requireUser } from '@/lib/server-auth';
import { z } from 'zod';
import { bumpUserCache } from '@/lib/redis';
const schema=z.object({title:z.string().trim().min(1).max(300).optional(),notes:z.string().max(5000).optional(),completed:z.boolean().optional(),priority:z.number().int().min(0).max(3).optional(),todoDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),position:z.number().int().min(0).optional(),visibility:z.enum(['private','friends']).optional(),roadmapId:z.string().uuid().nullable().optional()});
const dateOnly=(s:string)=>new Date(`${s}T00:00:00.000Z`);
export async function PATCH(req:Request,{params}:{params:Promise<{id:string}>}){try{const user=await requireUser();const {id}=await params;const input=schema.parse(await req.json());const updated=await withRls(user.id,async tx=>{const todo=await tx.todo.findFirst({where:{id,ownerId:user.id}});if(!todo)throw new Error('NOT_FOUND');const nextDate=input.todoDate?dateOnly(input.todoDate):todo.todoDate;let nextPosition=input.position;if(input.todoDate&&nextDate.getTime()!==todo.todoDate.getTime()&&nextPosition===undefined){const max=await tx.todo.aggregate({where:{ownerId:user.id,todoDate:nextDate},_max:{position:true}});nextPosition=(max._max.position??-1)+1;}const nextRoadmapId=input.roadmapId===undefined?todo.roadmapId:input.roadmapId; if(input.visibility==='friends'){if(!nextRoadmapId) throw new Error('FRIENDS_REQUIRES_ROADMAP'); const roadmap=await tx.roadmap.findFirst({where:{id:nextRoadmapId},select:{ownerId:true}}); if(!roadmap)throw new Error('NOT_FOUND'); if(roadmap.ownerId!==user.id){const share=await tx.roadmapShare.findFirst({where:{roadmapId:nextRoadmapId,userId:user.id}});if(!share)throw new Error('FRIENDS_REQUIRES_SHARED_ROADMAP')}} return tx.todo.update({where:{id},data:{title:input.title,notes:input.notes,completed:input.completed,priority:input.priority,position:nextPosition,todoDate:input.todoDate?nextDate:undefined,visibility:input.visibility,roadmapId:input.roadmapId===undefined?undefined:input.roadmapId}})});await bumpUserCache(user.id);return NextResponse.json({todo:updated})}catch(e){return errorResponse(e)}}
export async function DELETE(_req:Request,{params}:{params:Promise<{id:string}>}){try{const user=await requireUser();const {id}=await params;const result=await withRls(user.id,tx=>tx.todo.deleteMany({where:{id,ownerId:user.id}}));if(!result.count)return new Response('Not found',{status:404});await bumpUserCache(user.id);return NextResponse.json({ok:true})}catch(e){return errorResponse(e)}}
